export * from './did'
export * from './didDocument'
export * from './verificationMethod'
export * from './service'
export * from './publicKeyJwk'
export * from './publicKeyMultibase'
export * from './error'
export * from './verificationMethodTypes'
export * from './serviceTypes'
export * from './representations'

export * from './didResolution'
export * from './didUrlDereference'

export * from './schemas'
